#!/bin/bash

function _dep() {
    local cur=${COMP_WORDS[COMP_CWORD]}
    local prev=${COMP_WORDS[COMP_CWORD-1]}

    local commands="init status ensure version"

    case $prev in
    dep)
        COMPREPLY=($(compgen -W "$commands help" -- $cur))
        ;;
    help)
        COMPREPLY=($(compgen -W "$commands" -- $cur))
        ;;
    ensure)
        COMPREPLY=($(compgen -W "--add --update" -- $cur))
        ;;
    esac

    return 0
}

complete -F _dep dep
